#!/bin/sh

# To use, add this script and insert_w_tag to /usr/local/bin/, and give all execution privilages. Then, under keyboard shortcuts, set the shortcut to run the command copy_url_ff:
#
# sudo cp copy_url_ff /usr/local/bin/copy_url_ff
# sudo cp insert_w_tag /usr/local/bin/insert_w_tag
# sudo chmod a+x /usr/local/bin/copy_url_ff /usr/local/bin/insert_w_tag
#
# also need to run 
# sudo apt-get update
# sudo apt-get install xdotool
#
# Then, go to keyboard shortcuts and enter a custom keybinding to the command copy_url_ff, e.g. ctrl+shift+c here


# Sleep value used in script to prevent execution from tripping up
sleep_val=.2

# Function to press, then release the given key
press_and_release () {
    xdotool key $1
    sleep $sleep_val
    xdotool keyup $1
    sleep $sleep_val
}

# First, un-press the shortcut key for this script, in this case ctrl+shift+c
xdotool keyup ctrl+shift+c
sleep $sleep_val

# Then, press and release the shortcuts in firefox to highlight the url field and copy the contents
press_and_release "ctrl+l ctrl+c"

# Then, open a new terminal window
press_and_release "ctrl+alt+t"

# Type in the following string, which will enter a command to call insert_w_tag
xdotool type "insert_w_tag ~/Documents/ff_clip.txt "
sleep $sleep_val

# Paste the copied url from firefox
press_and_release "ctrl+shift+v"

# Enter a space, so the user can immediately type in the tags passed to insert_w_tag and press enter
xdotool type " "