#!/bin/sh

sleep_val=.2

press_and_release () {
    xdotool key $1
    sleep $sleep_val
    xdotool keyup $1
    sleep $sleep_val
}

xdotool keyup ctrl+shift+c

sleep $sleep_val

press_and_release "ctrl+l ctrl+c"
press_and_release "ctrl+alt+t"

xdotool type "insert_w_tag ~/Documents/ff_clip.txt "
sleep $sleep_val

press_and_release "ctrl+shift+v"

xdotool type " "