#!/bin/sh

# To use, add this script and insert_w_tag to /usr/local/bin/, and give all execution privilages. Then, under keyboard shortcuts, set the shortcut to run the command copy_url_ff:
#
# sudo cp copy_url_ff /usr/local/bin/copy_url_ff
# sudo cp insert_w_tag /usr/local/bin/insert_w_tag
# sudo chmod a+x /usr/local/bin/copy_url_ff /usr/local/bin/insert_w_tag


sleep_val=.2

press_and_release () {
    xdotool key $1
    sleep $sleep_val
    xdotool keyup $1
    sleep $sleep_val
}

xdotool keyup ctrl+shift+c
sleep $sleep_val

press_and_release "ctrl+l ctrl+c"
press_and_release "ctrl+alt+t"

xdotool type "insert_w_tag ~/Documents/ff_clip.txt "
sleep $sleep_val

press_and_release "ctrl+shift+v"

xdotool type " "